- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Converge
  hosts: molecule
  vars_files:
    - vars.yml
  gather_facts: true
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    #- name: Print some info
    #  ansible.builtin.assert:
    #    that: result.stdout | regex_search("^Linux")

    # TODO: We are not testing everything here, but it's a start
    - name: ClamAV
      ansible.builtin.import_tasks: tasks/clamav.yml
      # Slackware has ClamAV in SBo
      when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
    - name: AIDE
      ansible.builtin.import_tasks: tasks/aide.yml
      when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
    - name: Debian packages
      ansible.builtin.import_tasks: tasks/debian_packages.yml
    - name: Lynis
      ansible.builtin.import_tasks: tasks/lynis.yml
      when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
    - name: Banners
      ansible.builtin.import_tasks: tasks/banners.yml
    - name: PAM
      ansible.builtin.import_tasks: tasks/pam.yml
    - name: Services
      ansible.builtin.import_tasks: tasks/services.yml
    - name: Accounting services
      ansible.builtin.import_tasks: tasks/services-accounting.yml
    # Idempotence considerations:
    # * rkhunter needs to be ran after Debian packages, as it installs usbguard which affect rkhunter.conf
    # * accounting installs sysstat which brings /etc/cron.daily/sysstat
    # * services brings in cron for Molecule tests and causes rkhunter.conf generation to start monitoring /var/spool/cron/crontabs/*
    - name: rkhunter
      ansible.builtin.import_tasks: tasks/rkhunter.yml
      when: ansible_distribution == "Debian" or ansible_distribution == "Kali"
    - name: login_defs
      ansible.builtin.import_tasks: tasks/login_defs.yml
    - name: Permissions
      ansible.builtin.import_tasks: tasks/filesystem.yml
    - name: CA certificates
      ansible.builtin.import_tasks: tasks/ca-certs.yml
    - name: Misc
      ansible.builtin.import_tasks: tasks/misc.yml
    - name: Cgroup
      ansible.builtin.import_tasks: tasks/cgroup.yml
    - name: Display manager
      ansible.builtin.import_tasks: tasks/display_managers.yml
    - name: Kernel
      ansible.builtin.import_tasks: tasks/kernel.yml
    - name: Logging
      ansible.builtin.import_tasks: tasks/logging.yml

  handlers:
    - name: Handlers
      ansible.builtin.import_tasks: tasks/handlers.yml
