name: molecule
on: [push, pull_request]

env:
  ANSIBLE_FORCE_COLOR: '1'
  ANSIBLE_ALLOW_BROKEN_CONDITIONALS: '1'

jobs:
  molecule-slackware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        # Molecule was previously failing to run requirements.yml with permission denied. Hence we chown the lib dir.
        run: |
          pip install --user molecule[docker] molecule-plugins[docker]
          sudo chown -cR runner /usr/local/lib/python3.*
          molecule --version
      - name: Run Molecule
        run: molecule test
  molecule-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --user molecule[docker] molecule-plugins[docker]
          sudo chown -cR runner /usr/local/lib/python3.*
          molecule --version
      - name: Run Molecule
        run: molecule test --scenario-name debian
  molecule-kali:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --user molecule[docker] molecule-plugins[docker]
          sudo chown -cR runner /usr/local/lib/python3.*
          molecule --version
      - name: Run Molecule
        run: molecule test --scenario-name kali
