---
name: shellcheck
on: [push, pull_request]
env:
  ANSIBLE_FORCE_COLOR: '1'
jobs:
  profile_d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run Ansible playbook for shells
        run: ansible-playbook harden.yml --tags shells
      - name: Run ShellCheck
        run: shellcheck --shell=bash files/profile.d/* /etc/profile.d/tmout.sh tests/*.sh ./conf_file_differ.sh
